# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('picture_name', models.CharField(max_length=250, verbose_name='Picture')),
                ('price', models.DecimalField(decimal_places=2, default=2.0, max_digits=20, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=40, verbose_name='Quantity')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Parfum',
                'verbose_name_plural': 'Parfums',
            },
        ),
        migrations.CreateModel(
            name='FlavourQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.Flavour')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=250, unique=True, verbose_name='Code')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='flavourquantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour_quantity', to='vm.Order'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='order',
            field=models.ManyToManyField(related_name='orders', through='vm.FlavourQuantity', to='vm.Order'),
        ),
    ]
